java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/indeedeng__fdse__proctor
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/OpenNMS__fdse__opennms
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/apache__fdse__tomee/examples
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/apache__fdse__isis
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/hibernate__fdse__hibernate-search
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/bndtools__fdse__bnd
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/structr__fdse__structr/structr-modules
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/confluentinc__fdse__schema-registry
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/apache__fdse__nifi
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/takari__fdse__polyglot-maven
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/eclipse__fdse__smarthome
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/impetus-opensource__fdse__Kundera
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/openhab__fdse__openhab1-addons
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/JanusGraph__fdse__janusgraph
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/apache__fdse__zeppelin
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/naver__fdse__pinpoint
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/OpenHFT__fdse__Chronicle-Queue
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/OpenHFT__fdse__Chronicle-Map
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/javaee-samples__fdse__javaee7-samples
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/geoserver__fdse__geoserver
java -jar LibEffort-jar-with-dependencies.jar poj_DG_data0216 path_config0216.properties /home/hadoop/dfs/data/Workspace/projects_2_5/projects_all/apache__fdse__camel
